tcp_client.out, tcp_server01.out, tcp_server02.out, tcp_server03.out : tcp_client.c tcp_server01.c tcp_server02.c tcp_server03.c
	gcc tcp_client.c -o tcp_client.out
	gcc tcp_server01.c -o tcp_server01.out
	gcc tcp_server02.c -o tcp_server02.out
	gcc tcp_server03.c -lpthread -o tcp_server03.out

